fix: broken operation priorities for traced stores
effector/inspector pull request #41
Opened 2022-09-16 07:56 UTC by ilyaagarkov

I have used pattern from patronum/debug for tracing store but not sure I did everything right 

As I see this changes fix problems described here https://github.com/effector/logger/issues/100

2022-09-16 07:57 UTC, ilyaagarkov commented on src/index.ts
> +        before = copy(scope.state.current)
I'm not sure how we can use previous value with `createNode`

2022-09-16 12:28 UTC, zerobias requested changes
The idea itself should work, please fix imports

2022-09-16 12:28 UTC, zerobias commented on src/index.ts
> +import { createNode, Stack } from "effector/effector.cjs";
Dont use direct imports from specific bundles, please

2022-09-16 12:30 UTC, ilyaagarkov commented on src/index.ts
> +import { createNode, Stack } from "effector/effector.cjs";
IDEal auto imports sometimes lets down

2022-09-18 18:48 UTC, sergeysova approved these changes
Looks good.

2022-09-19 10:54 UTC, zerobias approved these changes

2022-09-19 10:58 UTC, merged